FROM wordpress:latest

RUN mkdir /code
WORKDIR /code
#COPY PROYECT FILES TO DOCKER
COPY theProject /code/
#INSTALL DEPENDENCIES IF NEEDED

#SET CONFIGURATIONS FLAGS
#ENV WORDPRESS_DB_HOST db:3306 
#ENV WORDPRESS_DB_USER wordpress 
#ENV WORDPRESS_DB_PASSWORD wordpress 
#ENV WORDPRESS_DB_NAME wordpress

EXPOSE 80

